# Generated by Django 4.1.2 on 2022-11-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_showpost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowPost',
        ),
    ]
