# Generated by Django 4.1.2 on 2022-12-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
